config/routes.rb
Rails.application.routes.draw do

  get 'coachings/create'

  devise_for :users

  authenticated :user do
  root to: 'languages#index', as: :authenticated_root
  end

  root 'home#land'

  resources :languages, only: [:index, :new, :create, :show] do
    resources :coachings, only: [:create,:update, :destroy]
  end

end

app/models/coaching.rb
# == Schema Information
#
# Table name: coachings
#
#  id          :integer          not null, primary key
#  pupil_id    :integer
#  mentor_id   :integer
#  language_id :integer
#  accepted    :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Coaching < ActiveRecord::Base
  belongs_to :pupil, class_name: User.name
  belongs_to :mentor, class_name: User.name
  belongs_to :language
  attr_accessor :mentor_email
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Language < ActiveRecord::Base
 
  has_many :coachings
  has_many :pupils, through: :coachings, source: :pupil
  
  has_many :mentors,through: :coachings, source: :mentor 

  has_many :pending_pupil_coachings, ->{ where(accepted: false)}, class_name: Coaching.name 
  has_many :accepted_pupil_coachings, ->{ where(accepted: true)}, class_name: Coaching.name 
  has_many :accepted_mentor_coachings, ->{ where(accepted: true)}, class_name: Coaching.name
 
  validates :name, presence: true


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  date_of_birth          :datetime
#  is_female              :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   
  has_many :languages
  # has_many :accepted_pupil_coachings, -> { where(accepted: true)}, foreign_key: :pupil_id,class_name: Coaching.name
  # has_many :pending_pupil_coachings, ->{ where(accepted: false)}, foreign_key: :pupil_id, class_name: Coaching.name 

  # has_many :accepted_mentor_coachings, ->{ where(accepted: true)}, foreign_key: :mentor_id, class_name: Coaching.name
  has_many :pending_mentor_coachings, ->{ where(accepted: false)}, foreign_key: :mentor_id, class_name: Coaching.name
  

  def teaching?(lang,user)
    Coaching.where(language: lang, mentor: self.id, pupil: user).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # configuration for devise controller

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            # params.require(:sign_up).permit(:name, :is_female, :date_of_birth, :email, :password, :password_confirmation)
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :is_female, :date_of_birth, :email, :password, :password_confirmation) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
            # params.require(:account_update).permit(:name, :is_female, :date_of_birth, :email, :password, :current_password )
        end
end

app/controllers/coachings_controller.rb
class CoachingsController < ApplicationController
  before_action :fetch_language
  before_action :fetch_coaching, only: [:update, :destroy]
  def create
    @new_coaching = @language.coachings.new 
    mentor_email = params[:coaching][:mentor_email]
    if ValidateEmail.validate(mentor_email) && mentor_email != current_user.email   
      @mentor = User.where(email: mentor_email).first
      if @mentor.nil?
        # Send an invitation request to mentor to join the app

      elsif @mentor.teaching?(@language,current_user)
        flash.now[:danger] = I18n.t 'flash_messages.coachings.already_invited'
      else
        create_invitation
      end
    else
      @invalid_email = true
    end 
  end

  def update
    @coaching.update_attribute(:accepted, true)
    flash[:success] = I18n.t 'flash_messages.coachings.accepted_success'
    redirect_to root_path
  end

private
    def fetch_language
      @language = Language.find(params[:language_id])
    end

    def fetch_coaching
      @coaching= @language.coachings.find(params[:id])

    end

    def create_invitation
      @new_coaching.pupil = current_user
      @new_coaching.mentor = @mentor
      @new_coaching.save!
      flash.now[:success] = I18n.t 'flash_messages.coachings.invite_success'
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:land]
  def land
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :fetch_language , only: [:show]
  def index
    @languages = Language.all   
    @pending_mentor_coaching_requests = current_user.pending_mentor_coachings
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to languages_path
    else
      render :new
    end
  end

  def show
    @coaching = Coaching.new
    @pending_pupil_coaching_requests = @language.pending_pupil_coachings.where(pupil: current_user)
    @accepted_pupil_coaching_requests = @language.accepted_pupil_coachings.where(pupil: current_user)

    @accepted_mentor_coaching_requests = @language.accepted_mentor_coachings.where(mentor: current_user)

    

  end

private
    def language_params
      params.require(:language).permit(:name, :description)
    end

    def fetch_language
      @language = Language.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def landing_page?
    controller_name == 'home' && action_name == 'land'
  end

  def flash_messages_tag
    #     <% flash.each do |fl| %>
    #   <div class="alert alert-<%=fl[0] %> alert-dismissible" role="alert">  
    #     <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    #     <%= fl[1] %>
    #   </div>  
    # <% end %>
    #   end
    
    str = " "
    flash.each do |fl|
      fl[0] = "success" if fl[0] == "notice" 
      fl[0] = "danger" if fl[0] == "error" || fl[0] == "alert"
      str+= content_tag(:div, class: "alert alert-#{fl[0]} alert-dismissible") do 
              content_tag(:button, class: "close", data: {dismiss: "alert"}) do
                content_tag(:span, raw("&times;")) 
              end + fl[1]
            end      
    end
    return raw(str)
  end
end

app/helpers/coachings_helper.rb
module CoachingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/coachings/_coaching.html.erb
  <div id="coaching">
    <div class="actions pull-right">
      <%= link_to "Accept", language_coaching_path(coaching.language,coaching),method: :patch, class: "btn btn-success btn-sm" %>
      <%= link_to "Reject", language_coaching_path(coaching.language,coaching),method: :delete, class: "btn btn-primary btn-sm" %>
    </div>
    <h4>
    <i><%= coaching.mentor.email %></i>, you have received a mentoring request to teach <b><%= coaching.language.name %></b> to <i><%= coaching.pupil.email %>(replace with name or email)</i>
    </h4>
    <p><%= coaching.language.description %></p>
    <p>
      Sent on: <%= coaching.created_at.strftime("%v") %>
    </p>

  </div>

app/views/coachings/create.js.erb
$('#choosepalModal .alert-danger').addClass('hidden');
<% if @invalid_email %>
  $('#choosepalModal .alert-danger').removeClass('hidden');
<% else %>
  $('#choosepalModal').modal('hide');
  $('#choosepalModal form')[0].reset();
  $('header .alert').remove();
  $('header').append('<%= j flash_messages_tag %>')
<% end %>

app/views/common/_header.html.erb
<header>
  
  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <%= link_to APP_NAME, root_path, class: "navbar-brand"  %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Dashboard", languages_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %><span class="caret"></span></a>
              <ul class="dropdown-menu">                
                <li><%= link_to "Edit profile", edit_user_registration_path %></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Signup",  new_user_registration_path, class: "btn btn-xs" %></li>
            <li><%= link_to "Login",  new_user_session_path, class: "btn btn-success" %></li>
          <%end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <%= flash_messages_tag %>
</header>

app/views/home/land.html.erb
<div id="land">
  <div class = "vcenter">
    <h3>
      Learn a Language Today.
      <i class="fa fa-share-alt-square" aria-hidden="true"></i>
    </h3>
    <i class="fa fa-facebook-square fa-lg" aria-hidden="true"></i>
    <%= link_to "Sign in using facebook", new_user_registration_path, class: "btn btn-outline" %>

  </div>


</div>

app/views/languages/_language.html.erb
<div class="container">
  <div class="panel panel-default pull-left">
    <div class="panel-heading">
      <%= link_to language.name, language_path(language) %>
    </div>
    <div class="panel-body">
      <%= language.description %>
    </div>
  </div>
</div>

app/views/languages/index.html.erb
<% if @pending_mentor_coaching_requests.any? %>
  <div id="authorship-invitations" class="well">
    <h3>Pending Mentorship Requests</h3>
    <%= render @pending_mentor_coaching_requests %>
  </div>
<% end %>


<div class="container">

  <row id="languages">
    <div class="col-md-4" id="language">
      <%= render @languages %>
    </div>
    <div class="col-md-8">
      <%= link_to "Add a language", new_language_path, class: "btn btn-info btn-md pull-right" %>
    </div>
  </row>
</div>

<!--

<div class="modal fade" id="addLanguage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Choose a Lang-Pal</h4>
      </div>
    </div>
  </div>
</div>
, data:{toggle:"modal", target:"#addLanguage"} -->

app/views/languages/new.html.erb
<div class="container">

<%= simple_form_for @language do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.submit class: "btn btn-info" %>
<% end %>

</div>

app/views/languages/show.html.erb
<div class="panel panel-default">
  <div class= "panel-heading">
  <%= @language.name %>
  </div>
</div>


<%= link_to "Add A Lang-Pal!", "#", class:"btn btn-success pull-right", data:{toggle:"modal", target:"#choosepalModal"} %>

<div id="mentors" >
  <h4>There are currently <b><%= @language.mentors.uniq.count %></b> mentors for this language</h4>
    <% @language.mentors.uniq.each do |mentor| %>
      <%= mentor.email %><br>
    <% end %>
</div>

<%  if @pending_pupil_coaching_requests.any? %>
  <div id="sent-pupil-requests">
    <h3>You sent <%= @pending_pupil_coaching_requests.count %> request for learning <%= @language.name %> to </h3>
      <%@pending_pupil_coaching_requests.each do |request| %>
      <%= request.mentor.email %>
      <%= link_to "Cancel Request", "#", class: "btn btn-danger" %>
      <%end %>
  </div>

<%end %>

<% if@accepted_pupil_coaching_requests.any? %>
  <div id="accepted-pupil-requests" >
    <h3>Your <%= @language.name %> pals are </h3>
    <%@accepted_pupil_coaching_requests.each do |request| %>
    <%= request.mentor.email %>
    <% end %>
  </div>
<%end %>


<% if @accepted_mentor_coaching_requests.any? %>
  <div id="accepted-mentor-requests">
    <h3>Your are mentoring <%= @language.name %> for</h3>
    <%@accepted_mentor_coaching_requests.each do |request| %>

    <%= request.pupil.email %> <br>
    <%end %>
  </div>
<%end %>





<!-- choose langpal Modal -->
<div class="modal fade" id="choosepalModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Choose a Lang-Pal</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@language, @coaching], remote: true do |f|%>
        <div class="alert alert-danger hidden" role="alert">Please enter a valid mentor email address,don't invite yourself!</div>
        <%= f.input :mentor_email, label: 'Enter Mentor Email you like to learn from', placeholder: 'user@domain.com' %>
        <%= f.button :submit, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slang</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,400italic' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/header' unless landing_page? %>
<div class =<%= "container" unless landing_page? %>>
  <%= yield %>
</div>

</body>
</html>